// <auto-generated />
namespace LapTrinhQuanLyDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration_People : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_People));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100721323_migration_People"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
