// <auto-generated />
namespace BTDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class altr_column_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altr_column_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100805397_altr_column_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
